<?php


return
    [
        'Alfa Romeo' => [
            'image' => 'uploads/mades/alfa-romeo.png',
            'moulds' => ['159', '166', 'Tonale', '146', 'Alfasud', 'Giulia', 'Montreal',
                'SZ', '8C', 'MiTo', 'Quadrifoglio', 'Sprint', 'Stelvio', '4C', '75', 'Crosswagon',
                'Giulietta', 'GT', 'Sportwagon', '147', '156', /*'Spider',*/ 'Brera', '145', '164', '2000',
                '33', '90', 'RZ', '155', '1750', 'Alfa 6', 'Alfetta', 'GTV', 'Others'
            ]
        ],
        'Audi' => [
            'image' => 'uploads/mades/audi.png',
            'moulds' => [
                '80', 'A1', 'A2', 'A3', 'A5', 'A7', 'A8', 'Q8', 'S7', 'A4', 'Cabriolet', 'Q1', 'RS2', 'S2',
                'S5', 'TTS', 'V8', 'A4 Allroad', 'A6', 'RS', 'RS Q3', 'A6 Allroad' /*,'Coupe'*/,
                'SQ5', 'SQ8', 'Allroad', 'Q2', 'Q7', 'RS Q5', 'RS5', 'RS6', 'S1', 'S4', 'TT', '200', '100',
                'Q3', 'QUATTRO', 'RS4', 'S3', 'S6', 'SQ7', '50', 'Q5', 'Q6', 'RS7', 'S8', 'SQ2', 'TT RS', 'Q4',
                'RS3', 'e - tron',/*'90',*/
            ],
        ],
        'BMW' => [
            'image' => 'uploads/mades/bmw.png',
            'moulds' => [
                'i8',
                '518',
                '520',
                '523',
                '524',
                '525',
                '528',
                '530',
                '535',
                '540',
                '550',
                'Active Hybrid 5',
                '214',
                '216',
                '218',
                '220',
                '225',
                '228',
                '230',
                '235',
                '240',
                '725',
                '728',
                '730',
                '732',
                '735',
                '740',
                '745',
                '750',
                '760',
                'Active Hybrid 7',
                'M1',
                'i3',
                '620',
                '628',
                '630',
                '633',
                '635',
                '640',
                '645',
                '650',
                '830',
                '840',
                '850',
                '2002',
                '315',
                '316',
                '318',
                '320',
                '323',
                '324',
                '325',
                '328',
                '330',
                '335',
                '340',
                'Active Hybrid 3',
                '418',
                '420',
                '425',
                '428',
                '430',
                '435',
                '440',
                '1er M Coupe',
                'M2',
                'M3',
                'M4',
                'M5',
                'M6',
                'M7',
                'M8',
                'M850',
                'Z1',
                'Z3',
                'Z3 M',
                'Z4',
                'Z4 M',
                'Z8',
                '114',
                '113',
                '118',
                '120',
                '123',
                '125',
                '130',
                '135',
                '140',
                'Active Hybrid X6',
                'X1',
                'X2 ',
                'X2 M',
                'X3',
                'X3 M',
                'X4',
                'X4 M',
                'X5',
                'X5 M',
                'X6',
                'X6 M',
                'X7',
                'X7 M'
            ],
        ],
        'Renault' => [
            'image' => 'uploads/mades/renault.png',
            'moulds' => [
                'Kangoo',
                'Safrane',
                'Clio',
                'Fluence',
                'Fluence Z.E.',
                'Fuego',
                'Koleos',
                'Logan',
                'Master',
                'Super 5',
                'Symbol',
                'Twizy',
                'ZOE',
                'Espace',
                'Messenger',
                'Modus',
                'Rapid',
                'Sandero',
                'Spider',
                'Twingo',
                'Coupe',
                'Kangoo Z.E.',
                'Latitude',
                'Sandero Stepway',
                'Kadjar',
                'Trafic',
                'Grand Modus',
                'Grand Scenic',
                'Laguna',
                'Megane',
                'P 1400',
                'Talisman',
                'Vel Satis',
                'Duster',
                'Grand Espace',
                'Wind',
                'Alaskan',
                'Alpine A310',
                'Alpine A610',
                'Alpine V6',
                'Captur',
                'Express',
                'Scenic',
                'Alpine A110',
                'Avantime',
                'Mascott'

            ]
        ],
    ];
