<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Str;

class Cart extends Model
{
    public $incrementing = false;
    use HasFactory;

    protected $fillable = [
        'cookie_id', 'user_id', 'plan_id', 'quantity'
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function (Cart $cart) {
            $cart->id = Str::uuid();
            $cart->cookie_id = $cart->getCookieId();
        });
        static::addGlobalScope('cookie_id', function (Builder $builder) {
            $builder->where('cookie_id', Cart::getCookieID());
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class,)->withDefault(
            ['name' => 'anonymous']
        );
    }

    public function plan()
    {
        return $this->belongsTo(Plan::class);
    }

    protected static function getCookieId()
    {
        $cookie_id = Cookie::get('cart_id');
        if (!$cookie_id) {
            $cookie_id = Str::uuid();
            Cookie::queue('cart_id', $cookie_id, 30 * 24 * 60);
        }
        return $cookie_id;
    }
}
